/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types
 * 
 * Usage:
 * CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 */
import "dotenv/config";

import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

import openapiTS, {astToString} from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH=path.resolve(__dirname, "../src/types/chatterbox-api.ts");

async function main() {
    const apiUrl=process.env.CHATTERBOX_API_URL?.trim();

    if(!apiUrl) {
        console.error("CHATTERBOX_API_URL is not set. Please set it in your environment variables.");
        process.exit(1);
    }

    const openApiUrl =`${apiUrl}/openapi.json`;
    console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

    const ast=await openapiTS(new URL(openApiUrl))
    const contents=astToString(ast);

    const outputDir=path.dirname(OUTPUT_PATH);
    if(!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, {recursive:true});
    }

    const header=`/**
 * This file is auto-generated from the Chatterbox TTS API OpenAPI spec.
 * Do not edit this file directly. Instead, run the sync-api script to regenerate it.
 * Generated from: ${openApiUrl}
 * Generated at: ${new Date().toISOString()}
 */
`;

fs.writeFileSync(OUTPUT_PATH, header+contents);
    console.log(`TypeScript types generated at: ${OUTPUT_PATH}`);
}

main().catch((err)=>{
    console.error("Error generating TypeScript types:", err);
    process.exit(1);
})
